### ISSUE TITLE
Errno24 Too many open files

### ISSUE THREAD

**Issue by tejeskifly** [arnaucode/coffeeMiner#13]
Hi,
If i try to run the script i'm get error:

`root@kali:~/coffeeMiner# python3 coffeeMiner.py 192.168.1.254
gateway: 192.168.1.254
victims:
['192.168.0.98']
Loading script: injector.py http://192.168.1.103:8000/script.js
Proxy server listening at http://0.0.0.0:8080
192.168.1.82:35207: clientconnect
192.168.1.103:43939: clientconnect
192.168.1.103:34049: clientconnect
192.168.1.103:46247: clientconnect
192.168.1.103:43913: clientconnect
192.168.1.103:59185: clientconnect
192.168.1.103:41345: clientconnect
192.168.1.103:33639: clientconnect
192.168.1.103:48165: clientconnect
192.168.1.103:51331: clientconnect
192.168.1.103:33005: clientconnect
192.168.1.103:37123: clientconnect
192.168.1.103:36267: clientconnect
192.168.1.103:37617: clientconnect
192.168.1.103:42669: clientconnect
192.168.1.103:59247: clientconnect
192.168.1.103:53215: clientconnect
192.168.1.103:38157: clientconnect
192.168.1.103:46405: clientconnect
192.168.1.103:55759: clientconnect
192.168.1.103:53633: clientconnect
192.168.1.103:51915: clientconnect
192.168.1.103:59833: clientconnect
192.168.1.103:36597: clientconnect
192.168.1.103:37375: clientconnect
192.168.1.103:44441: clientconnect
192.168.1.103:59193: clientconnect
192.168.1.103:45097: clientconnect
192.168.1.103:60293: clientconnect
192.168.1.103:60777: clientconnect
192.168.1.103:36073: clientconnect
192.168.1.103:50285: clientconnect
192.168.1.103:48741: clientconnect
192.168.1.103:34303: clientconnect
192.168.1.103:60339: clientconnect
192.168.1.103:40407: clientconnect
192.168.1.103:50603: clientconnect
192.168.1.103:34073: clientconnect
192.168.1.103:54461: clientconnect
192.168.1.103:37239: clientconnect
192.168.1.103:43605: clientconnect
192.168.1.103:35861: clientconnect
192.168.1.103:49485: clientconnect
192.168.1.103:44151: clientconnect
192.168.1.103:46573: clientconnect
192.168.1.103:32795: clientconnect
192.168.1.103:43393: clientconnect
192.168.1.103:58231: clientconnect
192.168.1.103:47151: clientconnect
192.168.1.103:39895: clientconnect
192.168.1.103:49041: clientconnect
192.168.1.103:49027: clientconnect
192.168.1.103:50727: clientconnect
192.168.1.103:33857: clientconnect
192.168.1.103:47033: clientconnect
192.168.1.103:47269: clientconnect
192.168.1.103:50661: clientconnect
192.168.1.103:47945: clientconnect
192.168.1.103:52287: clientconnect
192.168.1.103:51657: clientconnect
192.168.1.103:59463: clientconnect
192.168.1.103:35819: clientconnect
192.168.1.103:48881: clientconnect
192.168.1.103:35649: clientconnect
192.168.1.103:50411: clientconnect
192.168.1.103:37921: clientconnect
192.168.1.103:53373: clientconnect
192.168.1.103:51781: clientconnect
192.168.1.103:58017: clientconnect
192.168.1.103:59209: clientconnect
192.168.1.103:54243: clientconnect
192.168.1.103:34261: clientconnect
192.168.1.103:60833: clientconnect
192.168.1.103:59655: clientconnect
192.168.1.103:56061: clientconnect
192.168.1.103:33813: clientconnect
192.168.1.103:50551: clientconnect
192.168.1.103:54547: clientconnect
192.168.1.103:39891: clientconnect
192.168.1.103:60943: clientconnect
192.168.1.103:40283: clientconnect
192.168.1.103:50705: clientconnect
192.168.1.103:45451: clientconnect
192.168.1.103:45067: clientconnect
192.168.1.103:49507: clientconnect
192.168.1.103:47035: clientconnect
192.168.1.103:39371: clientconnect
192.168.1.103:45069: clientconnect
192.168.1.103:43001: clientconnect
192.168.1.103:50719: clientconnect
192.168.1.103:37325: clientconnect
192.168.1.103:53935: clientconnect
192.168.1.103:40761: clientconnect
192.168.1.103:51637: clientconnect
192.168.1.103:37735: clientconnect
192.168.1.103:39153: clientconnect
192.168.1.103:56705: clientconnect
192.168.1.103:45899: clientconnect
192.168.1.103:55817: clientconnect
192.168.1.103:50205: clientconnect
192.168.1.103:44049: clientconnect
192.168.1.103:45321: clientconnect
192.168.1.103:35411: clientconnect
192.168.1.103:57475: clientconnect
192.168.1.103:46539: clientconnect
192.168.1.103:50273: clientconnect
192.168.1.103:34193: clientconnect
192.168.1.103:55213: clientconnect
192.168.1.103:55471: clientconnect
192.168.1.103:38833: clientconnect
192.168.1.103:38497: clientconnect
192.168.1.103:60433: clientconnect
192.168.1.103:60441: clientconnect
192.168.1.103:36317: clientconnect
192.168.1.103:33567: clientconnect
192.168.1.103:50049: clientconnect
192.168.1.103:36377: clientconnect
192.168.1.103:49209: clientconnect
192.168.1.103:58287: clientconnect
192.168.1.103:45341: clientconnect
192.168.1.103:52963: clientconnect
192.168.1.103:56959: clientconnect
192.168.1.103:53489: clientconnect
192.168.1.103:44109: clientconnect
192.168.1.103:32959: clientconnect
192.168.1.103:42071: clientconnect
192.168.1.103:43241: clientconnect
192.168.1.103:60891: clientconnect
192.168.1.103:60359: clientconnect
192.168.1.103:48095: clientconnect
192.168.1.103:36575: clientconnect
192.168.1.103:56349: clientconnect
192.168.1.103:51497: clientconnect
192.168.1.103:45621: clientconnect
192.168.1.103:52857: clientconnect
192.168.1.103:50327: clientconnect
192.168.1.103:36035: clientconnect
192.168.1.103:52859: clientconnect
192.168.1.103:34571: clientconnect
192.168.1.103:47687: clientconnect
192.168.1.103:40479: clientconnect
192.168.1.103:40167: clientconnect
192.168.1.103:58413: clientconnect
192.168.1.103:40503: clientconnect
192.168.1.103:45269: clientconnect
192.168.1.103:33579: clientconnect
192.168.1.103:36269: clientconnect
192.168.1.103:41973: clientconnect
192.168.1.103:55589: clientconnect
192.168.1.103:35275: clientconnect
192.168.1.103:42317: clientconnect
192.168.1.103:57613: clientconnect
192.168.1.103:32777: clientconnect
192.168.1.103:47207: clientconnect
192.168.1.103:51213: clientconnect
192.168.1.103:39355: clientconnect
192.168.1.103:36057: clientconnect
192.168.1.103:60837: clientconnect
192.168.1.103:44761: clientconnect
192.168.1.103:45723: clientconnect
192.168.1.103:34581: clientconnect
192.168.1.103:50987: clientconnect
192.168.1.103:37697: clientconnect
192.168.1.103:51817: clientconnect
192.168.1.103:32943: clientconnect
192.168.1.103:36767: clientconnect
192.168.1.103:43149: clientconnect
192.168.1.103:41757: clientconnect
192.168.1.103:39441: clientconnect
192.168.1.103:49165: clientconnect
192.168.1.103:52525: clientconnect
192.168.1.103:47481: clientconnect
192.168.1.103:53123: clientconnect
192.168.1.103:47821: clientconnect
192.168.1.103:56671: clientconnect
192.168.1.103:39687: clientconnect
192.168.1.103:57161: clientconnect
192.168.1.103:49753: clientconnect
192.168.1.103:50459: clientconnect
192.168.1.103:57709: clientconnect
192.168.1.103:60425: clientconnect
192.168.1.103:54865: clientconnect
192.168.1.103:33531: clientconnect
192.168.1.103:49781: clientconnect
192.168.1.103:49577: clientconnect
192.168.1.103:51847: clientconnect
192.168.1.103:34791: clientconnect
192.168.1.103:60527: clientconnect
192.168.1.103:39133: clientconnect
192.168.1.103:41399: clientconnect
192.168.1.103:39665: clientconnect
192.168.1.103:52053: clientconnect
192.168.1.103:47285: clientconnect
192.168.1.103:59037: clientconnect
192.168.1.103:49951: clientconnect
192.168.1.103:37321: clientconnect
192.168.1.103:33557: clientconnect
192.168.1.103:41871: clientconnect
192.168.1.103:49795: clientconnect
192.168.1.103:42981: clientconnect
192.168.1.103:53351: clientconnect
192.168.1.103:47757: clientconnect
192.168.1.103:58397: clientconnect
192.168.1.103:32921: clientconnect
192.168.1.103:43721: clientconnect
192.168.1.103:41093: clientconnect
192.168.1.103:58039: clientconnect
192.168.1.103:56689: clientconnect
192.168.1.103:48645: clientconnect
192.168.1.103:33791: clientconnect
192.168.1.103:53937: clientconnect
192.168.1.103:33113: clientconnect
192.168.1.103:41301: clientconnect
192.168.1.103:46475: clientconnect
192.168.1.103:57237: clientconnect
192.168.1.103:57313: clientconnect
192.168.1.103:60107: clientconnect
192.168.1.103:35791: clientconnect
192.168.1.103:48297: clientconnect
192.168.1.103:40333: clientconnect
192.168.1.103:59347: clientconnect
192.168.1.103:59719: clientconnect
192.168.1.103:49719: clientconnect
192.168.1.103:45603: clientconnect
192.168.1.103:55365: clientconnect
192.168.1.103:39735: clientconnect
192.168.1.103:34157: clientconnect
192.168.1.103:41221: clientconnect
192.168.1.103:54357: clientconnect
192.168.1.103:44959: clientconnect
192.168.1.103:50435: clientconnect
192.168.1.103:33503: clientconnect
192.168.1.103:60187: clientconnect
192.168.1.103:60205: clientconnect
192.168.1.103:43531: clientconnect
192.168.1.103:53949: clientconnect
192.168.1.103:39305: clientconnect
192.168.1.103:55579: clientconnect
192.168.1.103:53729: clientconnect
192.168.1.103:39273: clientconnect
192.168.1.103:33561: clientconnect
192.168.1.103:34931: clientconnect
192.168.1.103:49637: clientconnect
192.168.1.103:33587: clientconnect
192.168.1.103:54633: clientconnect
192.168.1.103:46075: clientconnect
192.168.1.103:38455: clientconnect
192.168.1.103:34763: clientconnect
192.168.1.103:42009: clientconnect
192.168.1.103:55229: clientconnect
192.168.1.103:38719: clientconnect
192.168.1.103:40867: clientconnect
192.168.1.103:42059: clientconnect
192.168.1.103:50673: clientconnect
192.168.1.103:59857: clientconnect
192.168.1.103:59407: clientconnect
192.168.1.103:49477: clientconnect
192.168.1.103:35857: clientconnect
192.168.1.103:53021: clientconnect
192.168.1.103:35675: clientconnect
192.168.1.103:55541: clientconnect
192.168.1.103:50087: clientconnect
192.168.1.103:37599: clientconnect
192.168.1.103:39605: clientconnect
192.168.1.103:38431: clientconnect
192.168.1.103:45815: clientconnect
192.168.1.103:42557: clientconnect
192.168.1.103:34799: clientconnect
192.168.1.103:35733: clientconnect
192.168.1.103:49009: clientconnect
192.168.1.103:38763: clientconnect
192.168.1.103:37223: clientconnect
192.168.1.103:39303: clientconnect
192.168.1.103:55757: clientconnect
192.168.1.103:42701: clientconnect
192.168.1.103:49271: clientconnect
192.168.1.103:41419: clientconnect
192.168.1.103:44921: clientconnect
192.168.1.103:52419: clientconnect
192.168.1.103:34223: clientconnect
192.168.1.103:48361: clientconnect
192.168.1.103:48421: clientconnect
192.168.1.103:56219: clientconnect
192.168.1.103:35527: clientconnect
192.168.1.103:36823: clientconnect
192.168.1.103:52307: clientconnect
192.168.1.103:54377: clientconnect
192.168.1.103:55029: clientconnect
192.168.1.103:36199: clientconnect
192.168.1.103:48477: clientconnect
192.168.1.103:43361: clientconnect
192.168.1.103:34037: clientconnect
192.168.1.103:51461: clientconnect
192.168.1.103:44675: clientconnect
192.168.1.103:51301: clientconnect
192.168.1.103:32991: clientconnect
192.168.1.103:54299: clientconnect
192.168.1.103:46639: clientconnect
192.168.1.103:40375: clientconnect
192.168.1.103:36951: clientconnect
192.168.1.103:53853: clientconnect
192.168.1.103:40187: clientconnect
192.168.1.103:46561: clientconnect
192.168.1.103:48493: clientconnect
192.168.1.103:44591: clientconnect
192.168.1.103:43179: clientconnect
192.168.1.103:41397: clientconnect
192.168.1.103:59541: clientconnect
192.168.1.103:60599: clientconnect
192.168.1.103:58561: clientconnect
192.168.1.103:57081: clientconnect
192.168.1.103:42867: clientconnect
192.168.1.103:52007: clientconnect
192.168.1.103:53135: clientconnect
192.168.1.103:48937: clientconnect
192.168.1.103:54869: clientconnect
192.168.1.103:56075: clientconnect
192.168.1.103:39185: clientconnect
192.168.1.103:55317: clientconnect
192.168.1.103:51743: clientconnect
192.168.1.103:40779: clientconnect
192.168.1.103:50433: clientconnect
192.168.1.103:59353: clientconnect
192.168.1.103:48689: clientconnect
192.168.1.103:35023: clientconnect
192.168.1.103:55689: clientconnect
192.168.1.103:51971: clientconnect
192.168.1.103:49809: clientconnect
192.168.1.103:55113: clientconnect
192.168.1.103:41659: clientconnect
192.168.1.103:38437: clientconnect
192.168.1.103:59605: clientconnect
192.168.1.103:32775: clientconnect
192.168.1.103:38927: clientconnect
192.168.1.103:38787: clientconnect
192.168.1.103:46137: clientconnect
192.168.1.103:34433: clientconnect
192.168.1.103:40635: clientconnect
192.168.1.103:58025: clientconnect
192.168.1.103:49517: clientconnect
192.168.1.103:57445: clientconnect
192.168.1.103:57285: clientconnect
192.168.1.103:50271: clientconnect
192.168.1.103:37269: clientconnect
192.168.1.103:40491: clientconnect
192.168.1.103:57663: clientconnect
192.168.1.103:48703: clientconnect
192.168.1.103:56387: clientconnect
192.168.1.103:38009: clientconnect
192.168.1.103:42293: clientconnect
192.168.1.103:39973: clientconnect
192.168.1.103:59591: clientconnect
192.168.1.103:56841: clientconnect
192.168.1.103:48387: clientconnect
192.168.1.103:44873: clientconnect
192.168.1.103:55609: clientconnect
192.168.1.103:32781: clientconnect
192.168.1.103:39237: clientconnect
192.168.1.103:37969: clientconnect
192.168.1.103:37229: clientconnect
192.168.1.103:40081: clientconnect
192.168.1.103:39801: clientconnect
192.168.1.103:41835: clientconnect
192.168.1.103:45841: clientconnect
192.168.1.103:33093: clientconnect
192.168.1.103:50339: clientconnect
192.168.1.103:55195: clientconnect
192.168.1.103:40501: clientconnect
192.168.1.103:47729: clientconnect
192.168.1.103:54281: clientconnect
192.168.1.103:36335: clientconnect
192.168.1.103:46081: clientconnect
192.168.1.103:54777: clientconnect
192.168.1.103:43635: clientconnect
192.168.1.103:48981: clientconnect
192.168.1.103:37797: clientconnect
192.168.1.103:59007: clientconnect
192.168.1.103:52529: clientconnect
192.168.1.103:35625: clientconnect
192.168.1.103:44661: clientconnect
192.168.1.103:34769: clientconnect
192.168.1.103:57273: clientconnect
192.168.1.103:39255: clientconnect
192.168.1.103:39943: clientconnect
192.168.1.103:53019: clientconnect
192.168.1.103:53425: clientconnect
192.168.1.103:46027: clientconnect
192.168.1.103:36181: clientconnect
192.168.1.103:53981: clientconnect
192.168.1.103:60147: clientconnect
192.168.1.103:44305: clientconnect
192.168.1.103:60163: clientconnect
192.168.1.103:53023: clientconnect
192.168.1.103:50001: clientconnect
192.168.1.103:35973: clientconnect
192.168.1.103:40019: clientconnect
192.168.1.103:33119: clientconnect
192.168.1.103:38929: clientconnect
192.168.1.103:36611: clientconnect
192.168.1.103:48961: clientconnect
192.168.1.103:36555: clientconnect
192.168.1.103:49459: clientconnect
192.168.1.103:60513: clientconnect
192.168.1.103:59187: clientconnect
192.168.1.103:48365: clientconnect
192.168.1.103:52177: clientconnect
192.168.1.103:55673: clientconnect
192.168.1.103:52371: clientconnect
192.168.1.103:51289: clientconnect
192.168.1.103:45495: clientconnect
192.168.1.103:38415: clientconnect
192.168.1.103:38083: clientconnect
192.168.1.103:37939: clientconnect
192.168.1.103:34583: clientconnect
192.168.1.103:34695: clientconnect
192.168.1.103:54401: clientconnect
192.168.1.103:52831: clientconnect
192.168.1.103:47061: clientconnect
192.168.1.103:45381: clientconnect
192.168.1.103:58527: clientconnect
192.168.1.103:47163: clientconnect
192.168.1.103:54935: clientconnect
192.168.1.103:33245: clientconnect
192.168.1.103:39845: clientconnect
192.168.1.103:33979: clientconnect
192.168.1.103:40985: clientconnect
192.168.1.103:54955: clientconnect
192.168.1.103:56213: clientconnect
192.168.1.103:42883: clientconnect
192.168.1.103:43291: clientconnect
192.168.1.103:34653: clientconnect
192.168.1.103:57769: clientconnect
192.168.1.103:48065: clientconnect
192.168.1.103:59301: clientconnect
192.168.1.103:55059: clientconnect
192.168.1.103:49883: clientconnect
192.168.1.103:50655: clientconnect
192.168.1.103:38671: clientconnect
192.168.1.103:56901: clientconnect
192.168.1.103:39925: clientconnect
192.168.1.103:50363: clientconnect
192.168.1.103:51305: clientconnect
192.168.1.103:40011: clientconnect
192.168.1.103:41253: clientconnect
192.168.1.103:46979: clientconnect
192.168.1.103:57397: clientconnect
192.168.1.103:33663: clientconnect
192.168.1.103:40561: clientconnect
192.168.1.103:56685: clientconnect
192.168.1.103:55811: clientconnect
192.168.1.103:56631: clientconnect
192.168.1.103:37769: clientconnect
192.168.1.103:46053: clientconnect
192.168.1.103:35377: clientconnect
192.168.1.103:51841: clientconnect
192.168.1.103:49115: clientconnect
192.168.1.103:40941: clientconnect
192.168.1.103:48061: clientconnect
192.168.1.103:43569: clientconnect
192.168.1.103:46395: clientconnect
192.168.1.103:56413: clientconnect
192.168.1.103:49029: clientconnect
192.168.1.103:56751: clientconnect
192.168.1.103:37419: clientconnect
192.168.1.103:59403: clientconnect
192.168.1.103:47731: clientconnect
192.168.1.103:49789: clientconnect
192.168.1.103:43319: clientconnect
192.168.1.103:33949: clientconnect
192.168.1.103:33591: clientconnect
192.168.1.103:50839: clientconnect
192.168.1.103:38233: clientconnect
192.168.1.103:52877: clientconnect
192.168.1.103:58623: clientconnect
192.168.1.103:58385: clientconnect
192.168.1.103:45773: clientconnect
192.168.1.103:45535: clientconnect
192.168.1.103:37661: clientconnect
192.168.1.103:38553: clientconnect
192.168.1.103:36673: clientconnect
192.168.1.103:40343: clientconnect
192.168.1.103:55831: clientconnect
192.168.1.103:33775: clientconnect
192.168.1.103:36289: clientconnect
192.168.1.103:54913: clientconnect
192.168.1.103:48503: clientconnect
192.168.1.103:42233: clientconnect
192.168.1.103:46463: clientconnect
192.168.1.103:51663: clientconnect
192.168.1.103:35141: clientconnect
192.168.1.103:39351: clientconnect
192.168.1.103:40789: clientconnect
192.168.1.103:39841: clientconnect
192.168.1.103:54001: clientconnect
192.168.1.103:58703: clientconnect
192.168.1.103:53095: clientconnect
192.168.1.103:58101: clientconnect
192.168.1.103:58617: clientconnect
192.168.1.103:36127: clientconnect
192.168.1.103:56941: clientconnect
192.168.1.103:39331: clientconnect
192.168.1.103:58657: clientconnect
192.168.1.103:36873: clientconnect
192.168.1.103:36677: clientconnect
192.168.1.103:42877: clientconnect
192.168.1.103:46141: clientconnect
192.168.1.103:52541: clientconnect
192.168.1.103:42007: clientconnect
192.168.1.103:43305: clientconnect
192.168.1.103:59831: clientconnect
Exception in thread ServerThread (0.0.0.0:8080):
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
  File "/usr/lib/python3/dist-packages/mitmproxy/master.py", line 32, in run
  File "/usr/lib/python3/dist-packages/mitmproxy/net/tcp.py", line 951, in serve_forever
  File "/usr/lib/python3.6/socket.py", line 205, in accept
OSError: [Errno 24] Too many open files

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
  File "/usr/lib/python3/dist-packages/watchdog/observers/api.py", line 146, in run
  File "/usr/lib/python3/dist-packages/watchdog/observers/polling.py", line 91, in queue_events
  File "/usr/lib/python3/dist-packages/watchdog/observers/polling.py", line 74, in <lambda>
  File "/usr/lib/python3/dist-packages/watchdog/utils/dirsnapshot.py", line 236, in __init__
  File "/usr/lib/python3/dist-packages/watchdog/utils/dirsnapshot.py", line 213, in walk
OSError: [Errno 24] Too many open files: '.'`

Have you any idea whats the problem?
Regards

**Comment by tejeskifly** [comment]
I'd try it on a different network, and I think I find the problem.

On the first network, I already have a transparent proxy server which redirects the 80 port traffic to 8080 port. Is it possible to use the script with another proxy server on the same network? 

The proxy server on the network my MikroTik router default web proxy, I'm using it because I have multiple web servers behind the router.
