### ISSUE TITLE
WTF?!

### ISSUE THREAD

**Issue by LinuxSTAIN** [arnaucode/coffeeMiner#8]
Hi,
I cannot figure this issue out! In coffeeMiner.py I had to change the location of mitmdump to /usr/bin/mitmdump. No big deal. But I am getting this error. Can you please shed some light on what I need to do? Thank You!!
`Traceback (most recent call last):
  File "/usr/bin/mitmdump", line 11, in <module>
    load_entry_point('mitmproxy==2.0.2', 'console_scripts', 'mitmdump')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/main.py", line 12, in <module>
    from mitmproxy.tools import cmdline  # noqa
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/cmdline.py", line 10, in <module>
    from mitmproxy.addons import view
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/__init__.py", line 7, in <module>
    from mitmproxy.addons import onboarding
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/onboarding.py", line 2, in <module>
    from mitmproxy.addons.onboardingapp import app
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/onboardingapp/app.py", line 8, in <module>
    from mitmproxy.proxy import config
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/__init__.py", line 2, in <module>
    from .root_context import RootContext
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/root_context.py", line 3, in <module>
    from mitmproxy.proxy import protocol
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/protocol/__init__.py", line 39, in <module>
    from .tls import TlsClientHello
  File "/usr/lib/python3/dist-packages/mitmproxy/proxy/protocol/tls.py", line 7, in <module>
    from mitmproxy.contrib import tls_parser
  File "/usr/lib/python3/dist-packages/mitmproxy/contrib/tls_parser.py", line 8, in <module>
    from construct import (Array, Bytes, Struct, UBInt16, UBInt32, UBInt8, PascalString, Embed, TunnelAdapter, GreedyRange, Switch, OptionalGreedyRange, Optional)
ImportError: cannot import name 'UBInt16'
`

**Comment by LinuxSTAIN** [comment]
I was able to reproduce this error by passing mitmproxy a bad command.

**Comment by dotaxis** [comment]
Why did you move mitmproxy and from where?

**Comment by LinuxSTAIN** [comment]
When trying to run the coffeeMiner.py I kept getting "mitmdump not found" error. I changed the code in coffeeMiner.py to point to where mitmdump is located at /usr/bin/mitmdump , insead of ~/.local/bin/mitmdump   Maybe this is the wrong approach?

**Comment by dotaxis** [comment]
No, that should be fine. That's mitmdump, though, and you only changed the command. Moving the actual mitmdump to a different folder would be bad. Hence my confusion.

Did you edit line 28 in coffeeMiner.py to use your IP?

**Comment by LinuxSTAIN** [comment]
yes i did. Sorry I edited my first post to mitmdump not mitmproxy.

**Comment by LinuxSTAIN** [comment]
it looks like its an issue with mitmproxy. when i try and execute the command mitmproxy --version i get the same error.
